apiVersion: v1
kind: Pod
metadata:
  name: command-demo
  labels:
    purpose: demonstrate-command
spec:
  containers:
  - name: command-demo-container
    image: harbor.localdomain/mytest/rs-test:lis.5
    command: ["/usr/bin/web"]
    args: ["-nvlp 5555"]
  restartPolicy: OnFailure
